// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarItems: typeof import('vuetify/lib')['VToolbarItems']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export { }
